# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastroTurma.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless você sabe o que está fazendo.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CadastroTurmaWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Label para o nome da turma
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_nome.setObjectName("label_nome")

        # Campo de texto para o nome da turma
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(10, 50, 380, 30))
        self.lineEdit_nome.setObjectName("lineEdit_nome")

        # Label para o horário da turma
        self.label_horario = QtWidgets.QLabel(self.centralwidget)
        self.label_horario.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_horario.setObjectName("label_horario")

        # Campo de texto para o horário da turma
        self.lineEdit_horario = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_horario.setGeometry(QtCore.QRect(10, 110, 380, 30))
        self.lineEdit_horario.setObjectName("lineEdit_horario")

        # Label para a modalidade da turma
        self.label_modalidade = QtWidgets.QLabel(self.centralwidget)
        self.label_modalidade.setGeometry(QtCore.QRect(10, 150, 121, 16))
        self.label_modalidade.setObjectName("label_modalidade")

        # Campo de texto para a modalidade da turma
        self.lineEdit_modalidade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_modalidade.setGeometry(QtCore.QRect(10, 170, 380, 30))
        self.lineEdit_modalidade.setObjectName("lineEdit_modalidade")

        # Label para o ID da academia
        self.label_academia_id = QtWidgets.QLabel(self.centralwidget)
        self.label_academia_id.setGeometry(QtCore.QRect(10, 210, 121, 16))
        self.label_academia_id.setObjectName("label_academia_id")

        # Campo de texto para o ID da academia
        self.lineEdit_academia_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_academia_id.setGeometry(QtCore.QRect(10, 230, 380, 30))
        self.lineEdit_academia_id.setObjectName("lineEdit_academia_id")

        # Label para o ID do professor
        self.label_professor_id = QtWidgets.QLabel(self.centralwidget)
        self.label_professor_id.setGeometry(QtCore.QRect(10, 270, 121, 16))
        self.label_professor_id.setObjectName("label_professor_id")

        # Campo de texto para o ID do professor
        self.lineEdit_professor_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_professor_id.setGeometry(QtCore.QRect(10, 290, 380, 30))
        self.lineEdit_professor_id.setObjectName("lineEdit_professor_id")

        # Botão de salvar
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(10, 330, 80, 30))
        self.pushButton_salvar.setObjectName("pushButton_salvar")

        # Botão de cancelar
        self.pushButton_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(100, 330, 80, 30))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro de Turma"))
        self.label_nome.setText(_translate("MainWindow", "Nome da Turma:"))
        self.label_horario.setText(_translate("MainWindow", "Horário:"))
        self.label_modalidade.setText(_translate("MainWindow", "Modalidade:"))
        self.label_academia_id.setText(_translate("MainWindow", "ID da Academia:"))
        self.label_professor_id.setText(_translate("MainWindow", "ID do Professor:"))
        self.pushButton_salvar.setText(_translate("MainWindow", "Salvar"))
        self.pushButton_cancelar.setText(_translate("MainWindow", "Cancelar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CadastroTurmaWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
