# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastroUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroUsuarioDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)  # Aumentei o tamanho da janela para acomodar os novos campos

        self.btnRegistra = QtWidgets.QPushButton(Dialog)
        self.btnRegistra.setGeometry(QtCore.QRect(50, 320, 91, 23))
        self.btnRegistra.setObjectName("btnRegistra")
        self.btnCancela = QtWidgets.QPushButton(Dialog)
        self.btnCancela.setGeometry(QtCore.QRect(270, 320, 75, 23))
        self.btnCancela.setObjectName("btnCancela")

        # Campo Nome
        self.label_nome = QtWidgets.QLabel(Dialog)
        self.label_nome.setGeometry(QtCore.QRect(50, 80, 91, 16))
        self.label_nome.setObjectName("label_nome")
        self.lineEdit_nome = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nome.setGeometry(QtCore.QRect(50, 100, 301, 20))
        self.lineEdit_nome.setObjectName("lineEdit_nome")

        # Campo Email
        self.label_email = QtWidgets.QLabel(Dialog)
        self.label_email.setGeometry(QtCore.QRect(50, 130, 91, 16))
        self.label_email.setObjectName("label_email")
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_email.setGeometry(QtCore.QRect(50, 150, 301, 20))
        self.lineEdit_email.setObjectName("lineEdit_email")

        # Campo Senha
        self.label_senha = QtWidgets.QLabel(Dialog)
        self.label_senha.setGeometry(QtCore.QRect(50, 180, 91, 16))
        self.label_senha.setObjectName("label_senha")
        self.lineEdit_senha = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_senha.setGeometry(QtCore.QRect(50, 200, 301, 20))
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")

        # Checkbox Administrador
        self.checkBoxAdmin = QtWidgets.QCheckBox(Dialog)
        self.checkBoxAdmin.setGeometry(QtCore.QRect(50, 240, 301, 20))
        self.checkBoxAdmin.setObjectName("checkBoxAdmin")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 381, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Register", "Cadastro"))
        self.btnRegistra.setText(_translate("Dialog", "REGISTRAR-SE"))
        self.btnCancela.setText(_translate("Dialog", "CANCELAR"))
        self.label_nome.setText(_translate("Dialog", "Nome:"))
        self.label_email.setText(_translate("Dialog", "E-mail:"))
        self.label_senha.setText(_translate("Dialog", "Senha:"))
        self.checkBoxAdmin.setText(_translate("Dialog", "Esta conta é de administrador"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">INTELLIGYM - SISTEMA DE GERENCIAMENTO DE ACADEMIAS</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_CadastroUsuarioDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
