# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastroAcademia.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know o que está fazendo.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroAcademiaDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label_nome = QtWidgets.QLabel(Dialog)
        self.label_nome.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_nome.setObjectName("label_nome")

        self.lineEdit_nome = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nome.setGeometry(QtCore.QRect(10, 50, 380, 30))
        self.lineEdit_nome.setObjectName("lineEdit_nome")

        self.label_telefone = QtWidgets.QLabel(Dialog)
        self.label_telefone.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_telefone.setObjectName("label_telefone")

        self.lineEdit_telefone = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_telefone.setGeometry(QtCore.QRect(10, 110, 380, 30))
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")

        self.label_endereco = QtWidgets.QLabel(Dialog)
        self.label_endereco.setGeometry(QtCore.QRect(10, 150, 121, 16))
        self.label_endereco.setObjectName("label_endereco")

        self.lineEdit_endereco = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_endereco.setGeometry(QtCore.QRect(10, 170, 380, 30))
        self.lineEdit_endereco.setObjectName("lineEdit_endereco")

        self.pushButton_salvar = QtWidgets.QPushButton(Dialog)
        self.pushButton_salvar.setGeometry(QtCore.QRect(10, 220, 80, 30))
        self.pushButton_salvar.setObjectName("pushButton_salvar")

        self.pushButton_cancelar = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(100, 220, 80, 30))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cadastro de Academia"))
        self.label_nome.setText(_translate("Dialog", "Nome da Academia:"))
        self.label_telefone.setText(_translate("Dialog", "Telefone:"))
        self.label_endereco.setText(_translate("Dialog", "Endereço:"))
        self.pushButton_salvar.setText(_translate("Dialog", "Salvar"))
        self.pushButton_cancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_CadastroAcademiaDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
