# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastroAluno.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you sabe o que está fazendo.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CadastroAlunoDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 450)
        
        # Criando o layout principal
        self.layout = QtWidgets.QVBoxLayout(Dialog)

        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")

        # Label para o nome do aluno
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_nome.setObjectName("label_nome")

        # Campo de texto para o nome do aluno
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(10, 50, 380, 30))
        self.lineEdit_nome.setObjectName("lineEdit_nome")

        # Label para o email do aluno
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_email.setObjectName("label_email")

        # Campo de texto para o email do aluno
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(10, 110, 380, 30))
        self.lineEdit_email.setObjectName("lineEdit_email")

        # Label para o telefone do aluno
        self.label_telefone = QtWidgets.QLabel(self.centralwidget)
        self.label_telefone.setGeometry(QtCore.QRect(10, 150, 121, 16))
        self.label_telefone.setObjectName("label_telefone")

        # Campo de texto para o telefone do aluno
        self.lineEdit_telefone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_telefone.setGeometry(QtCore.QRect(10, 170, 380, 30))
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")

        # Label para a data de nascimento do aluno
        self.label_data_nasc = QtWidgets.QLabel(self.centralwidget)
        self.label_data_nasc.setGeometry(QtCore.QRect(10, 210, 121, 16))
        self.label_data_nasc.setObjectName("label_data_nasc")

        # Campo de data para a data de nascimento do aluno
        self.dateEdit_data_nasc = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_data_nasc.setGeometry(QtCore.QRect(10, 230, 380, 30))
        self.dateEdit_data_nasc.setObjectName("dateEdit_data_nasc")

        # Label para a academia
        self.label_academia = QtWidgets.QLabel(self.centralwidget)
        self.label_academia.setGeometry(QtCore.QRect(10, 270, 121, 16))
        self.label_academia.setObjectName("label_academia")

        # Campo de texto para a academia
        self.lineEdit_academia = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_academia.setGeometry(QtCore.QRect(10, 290, 380, 30))
        self.lineEdit_academia.setObjectName("lineEdit_academia")

        # Label para a turma
        self.label_turma = QtWidgets.QLabel(self.centralwidget)
        self.label_turma.setGeometry(QtCore.QRect(10, 330, 121, 16))
        self.label_turma.setObjectName("label_turma")

        # Campo de texto para a turma
        self.lineEdit_turma = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_turma.setGeometry(QtCore.QRect(10, 350, 380, 30))
        self.lineEdit_turma.setObjectName("lineEdit_turma")

        # Botão de salvar
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(10, 390, 80, 30))
        self.pushButton_salvar.setObjectName("pushButton_salvar")

        # Botão de cancelar
        self.pushButton_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(100, 390, 80, 30))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")

        # Adicionando o widget central ao layout
        self.layout.addWidget(self.centralwidget)

        # Ajuste final do layout
        Dialog.setLayout(self.layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cadastro de Aluno"))
        self.label_nome.setText(_translate("Dialog", "Nome:"))
        self.label_email.setText(_translate("Dialog", "Email:"))
        self.label_telefone.setText(_translate("Dialog", "Telefone:"))
        self.label_data_nasc.setText(_translate("Dialog", "Data Nascimento:"))
        self.label_academia.setText(_translate("Dialog", "Academia:"))
        self.label_turma.setText(_translate("Dialog", "Turma:"))
        self.pushButton_salvar.setText(_translate("Dialog", "Salvar"))
        self.pushButton_cancelar.setText(_translate("Dialog", "Cancelar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_CadastroAlunoDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
